[package]
name = "i"
version = "0.1.0"
authors = ["Nikita Zdanovitch <nikita.zdanovitch@trocafone.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
glam = { version = "0.12", features=["mint"] }
pyxel = "0.2"
legion = "0.3"
