[package]
name = "i"
version = "0.1.0"
authors = ["Nikita Zdanovitch <nikita.zdanovitch@trocafone.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
glam = { version = "0.12", features=["mint"] }
pyxel = { version = "0.2", features=["images"] }
legion = "0.4"
image = "0.22"
rapier2d = { version = "0.6", features=["simd-stable"] }
crossbeam-channel = "0.5"
regex = "1"

[patch.crates-io]
pyxel = { git = 'https://github.com/Jbat1Jumper/pyxel', features=["images"] }
